/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.AOOPProject;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import com.formdev.flatlaf.*;

/**
 *
 * @author twistingcamel
 */
public class MainWindow extends javax.swing.JFrame {
	/**
	 * Creates new form MainWindow
	 */
	public MainWindow() {
		initComponents();
		((FileContentsDisplayer) displayersTab.getComponentAt(0)).update();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonsNavigationPanel = new javax.swing.JPanel();
        dirBackButton = new DirBackButton(this);
        dirForwardButton1 = new DirForwardButton(this);
        dirUpButton = new DirUpButton(this);
        typeAddButton = new javax.swing.JButton();
        pathNavigationPanel = new javax.swing.JPanel();
        pathScrollPane = new javax.swing.JScrollPane();
        pathPanel = new javax.swing.JPanel();
        typesScrollPanel = new javax.swing.JScrollPane();
        typesPanel = new javax.swing.JPanel();
        Downloads = null;
        Pictures = null;
        displayersTab = new javax.swing.JTabbedPane();
        fileContentsDisplayer1 = new org.AOOPProject.FileContentsDisplayer(new File("~"));
        menuBar = new javax.swing.JMenuBar();
        menuView = new javax.swing.JMenu();
        viewModeMenu = new javax.swing.JMenu();
        jMenuItem1 = new ViewMenuItem(this, new IconsOnlyView());
        jMenuItem3 = new ViewMenuItem(this, new DetailsView());
        viewModeMenu1 = new javax.swing.JMenu();
        LightThemeItem = new javax.swing.JMenuItem();
        DarkThemeItem = new javax.swing.JMenuItem();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        jButton3.setText("jButton3");
        jButton3.setName("jButton3"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        buttonsNavigationPanel.setBorder(new com.formdev.flatlaf.ui.FlatBorder());
        buttonsNavigationPanel.setName("buttonsNavigationPanel"); // NOI18N

        dirBackButton.setText("<");
        dirBackButton.setMaximumSize(new java.awt.Dimension(30, 30));
        dirBackButton.setMinimumSize(new java.awt.Dimension(30, 30));
        dirBackButton.setName("dirBackButton"); // NOI18N
        dirBackButton.setPreferredSize(new java.awt.Dimension(30, 30));
        buttonsNavigationPanel.add(dirBackButton);

        dirForwardButton1.setText(">");
        dirForwardButton1.setMaximumSize(new java.awt.Dimension(30, 30));
        dirForwardButton1.setMinimumSize(new java.awt.Dimension(30, 30));
        dirForwardButton1.setName("dirForwardButton1"); // NOI18N
        dirForwardButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        buttonsNavigationPanel.add(dirForwardButton1);

        dirUpButton.setText("^");
        dirUpButton.setMaximumSize(new java.awt.Dimension(30, 30));
        dirUpButton.setMinimumSize(new java.awt.Dimension(30, 30));
        dirUpButton.setName("dirUpButton"); // NOI18N
        dirUpButton.setPreferredSize(new java.awt.Dimension(30, 30));
        buttonsNavigationPanel.add(dirUpButton);

        typeAddButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        typeAddButton.setText("+");
        typeAddButton.setBorder(null);
        typeAddButton.setMaximumSize(new java.awt.Dimension(30, 30));
        typeAddButton.setMinimumSize(new java.awt.Dimension(30, 30));
        typeAddButton.setName("typeAddButton"); // NOI18N
        typeAddButton.setPreferredSize(new java.awt.Dimension(30, 30));
        typeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeAddButtonActionPerformed(evt);
            }
        });
        buttonsNavigationPanel.add(typeAddButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(buttonsNavigationPanel, gridBagConstraints);

        pathNavigationPanel.setBorder(new com.formdev.flatlaf.ui.FlatMenuBarBorder());
        pathNavigationPanel.setName("pathNavigationPanel"); // NOI18N
        pathNavigationPanel.setLayout(new java.awt.GridLayout(1, 0));

        pathScrollPane.setName("pathScrollPane"); // NOI18N

        pathPanel.setName("pathPanel"); // NOI18N
        pathScrollPane.setViewportView(pathPanel);

        pathNavigationPanel.add(pathScrollPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(pathNavigationPanel, gridBagConstraints);

        typesScrollPanel.setName("typesScrollPanel"); // NOI18N

        typesPanel.setBorder(new com.formdev.flatlaf.ui.FlatBorder());
        typesPanel.setName("typesPanel"); // NOI18N
        typesPanel.setLayout(new javax.swing.BoxLayout(typesPanel, javax.swing.BoxLayout.Y_AXIS));

        Downloads = new ExactNavigationButton(this, new RealFileSystemPopulator("Downloads", "~/Downloads"));
        Downloads.setText("Downloads");
        Downloads.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Downloads.setMaximumSize(new java.awt.Dimension(10000, 31));
        Downloads.setMinimumSize(new java.awt.Dimension(10000, 31));
        Downloads.setName("Downloads"); // NOI18N
        typesPanel.add(Downloads);

        Pictures = new ExactNavigationButton(this, new VirtualFileSystemPopulator("Pictures", GlobFileFilter.class, new String[]{"~/Downloads/*.jpeg", "~/Downloads/*.png", "~/Pictures/*.jpeg", "~/Pictures/*.png", "~/Downloads/*image*", "~/Pictures/*image*"}));
        Pictures.setText("Pictures");
        Pictures.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Pictures.setMaximumSize(new java.awt.Dimension(10000, 31));
        Pictures.setMinimumSize(new java.awt.Dimension(10000, 31));
        Pictures.setName("Pictures"); // NOI18N
        typesPanel.add(Pictures);
        for (File i : java.io.File.listRoots()) {
            ExactNavigationButton button = new ExactNavigationButton(this, new RealFileSystemPopulator(i));
            button.setText(i.getName());

            button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

            button.setMaximumSize(new java.awt.Dimension(10000, 31));

            button.setMinimumSize(new java.awt.Dimension(10000, 31));

            button.setName(i.getName()); // NOI18N
            typesPanel.add(button);
        }

        typesScrollPanel.setViewportView(typesPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(typesScrollPanel, gridBagConstraints);

        displayersTab.setName("displayersTab"); // NOI18N
        displayersTab.addTab("tab1", fileContentsDisplayer1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(displayersTab, gridBagConstraints);

        menuBar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        menuBar.setName("menuBar"); // NOI18N

        menuView.setBackground(new java.awt.Color(39, 43, 51));
        menuView.setText("View");
        menuView.setName("menuView"); // NOI18N

        viewModeMenu.setText("View mode");
        viewModeMenu.setName("viewModeMenu"); // NOI18N

        jMenuItem1.setText("Icons only");
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        viewModeMenu.add(jMenuItem1);

        jMenuItem3.setText("Details");
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        viewModeMenu.add(jMenuItem3);

        menuView.add(viewModeMenu);

        viewModeMenu1.setText("Theme");
        viewModeMenu1.setName("viewModeMenu1"); // NOI18N

        LightThemeItem.setText("Light");
        LightThemeItem.setName("LightThemeItem"); // NOI18N
        LightThemeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LightThemeItemActionPerformed(evt);
            }
        });
        viewModeMenu1.add(LightThemeItem);

        DarkThemeItem.setText("Dark");
        DarkThemeItem.setName("DarkTheme"); // NOI18N
        DarkThemeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DarkThemeItemActionPerformed(evt);
            }
        });
        viewModeMenu1.add(DarkThemeItem);

        menuView.add(viewModeMenu1);

        menuBar.add(menuView);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	// light theme
	private void LightThemeItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem7ActionPerformed
		try {
			UIManager.setLookAndFeel(new FlatLightLaf());
			SwingUtilities.updateComponentTreeUI(this);
			revalidate();
			validate();
			repaint();
		} catch (UnsupportedLookAndFeelException e) {
			System.err.println(e.getMessage());
		}
	}// GEN-LAST:event_jMenuItem7ActionPerformed

	// dark theme
	private void DarkThemeItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem6ActionPerformed
		// change theme to dark
		try {
			UIManager.setLookAndFeel(new FlatDarkLaf());
			SwingUtilities.updateComponentTreeUI(this);
			revalidate();
			validate();
			// for(var i : )
			repaint();
		} catch (UnsupportedLookAndFeelException e) {
			System.err.println(e.getMessage());
		}

	}// GEN-LAST:event_jMenuItem6ActionPerformed

	private void typeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dirUpButton2ActionPerformed
		JFileChooser chooser = new JFileChooser();
		chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		chooser.setMultiSelectionEnabled(true);
		int returnVal = chooser.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File[] files = chooser.getSelectedFiles();
			for (File file : files) {
				addType(file);
			}
		}
	}// GEN-LAST:event_dirUpButton2ActionPerformed

	private void addType(File file) {
		String name = file.getName();
		String path = file.getAbsolutePath();
		JButton button = new ExactNavigationButton(MainWindow.this, new RealFileSystemPopulator(new File(path)),
				name);
		button.setHorizontalAlignment(SwingConstants.LEFT);
		button.setMaximumSize(new Dimension(10000, 31));
		button.setMinimumSize(new Dimension(10000, 31));
		button.setName(name);
		typesPanel.add(button);
		typesPanel.revalidate();
		typesPanel.repaint();

	}

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel.
		 * For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */

		try {
			UIManager.setLookAndFeel(new FlatLightLaf());
		} catch (Exception ex) {
			System.err.println("Failed to initialize LaF");
		}

		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainWindow().setVisible(true);
			}
		});
	}

	protected void typeButtonActionPerformed(ActionEvent evt) {
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DarkThemeItem;
    private javax.swing.JButton Downloads;
    private javax.swing.JMenuItem LightThemeItem;
    private javax.swing.JButton Pictures;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel buttonsNavigationPanel;
    private javax.swing.JButton dirBackButton;
    private javax.swing.JButton dirForwardButton1;
    private javax.swing.JButton dirUpButton;
    private javax.swing.JTabbedPane displayersTab;
    private org.AOOPProject.FileContentsDisplayer fileContentsDisplayer1;
    private javax.swing.JButton jButton3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuView;
    private javax.swing.JPanel pathNavigationPanel;
    private javax.swing.JPanel pathPanel;
    private javax.swing.JScrollPane pathScrollPane;
    private javax.swing.JButton typeAddButton;
    private javax.swing.JPanel typesPanel;
    private javax.swing.JScrollPane typesScrollPanel;
    private javax.swing.JMenu viewModeMenu;
    private javax.swing.JMenu viewModeMenu1;
    // End of variables declaration//GEN-END:variables

	public JPanel getPathPanel() {
		return pathPanel;
	}
}
